[application]

# App (Project) Name
name = "rbt-visualiser"

[web.app]

# HTML title tag content
title = "rbt-visualiser"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
  "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css",
  "assets/tailwind.css",
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
